### PR TITLE
Timer Added for wait after 25 Requests.

### LINKED ISSUE #77: Add timer for 10 seconds to know how much seconds are left.
Every api keys shared the quota so this doesn't work.

Updating this request to Add a timer to Start for requests

### PR DESCRIPTION
**Pull request by hammadsajid786**

### CODE REVIEW

File: BinanceBot/BinanceBot/PlaceOrders.cs [hunk 1]
```diff
@@ -37,6 +38,9 @@ public PlaceOrders()
             _binanceRequestOrdersLimit = int.Parse(System.Configuration.ConfigurationManager.AppSettings["BinanceRequestOrdersLimit"]);
         }
 
+
+        private ManualResetEvent _manualResetEvent = new ManualResetEvent(false);
```
Comment (hammadsajid786) [inline BinanceBot/BinanceBot/PlaceOrders.cs:42]: Remove it if not needeed

**Review by hammadsajid786 — COMMENTED** [review]
Please check my comments and them merge it .
